name: mimic-sdoh
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pyyaml=6.0.1
  - tqdm=4.66.2
  - pip:
      - xgboost==2.0.3
